### ISSUE TITLE
Fix headlines on mobile

### ISSUE THREAD

**Issue by itsjoekent** [deadlybutter/bernie_economics#1]
- [ ] Extends outside of page
- [ ] Not vertically centered & touches bottom w/ large gap at top

**Comment by rthbound** [comment]
have you been to Coders For Sanders?

**Comment by itsjoekent** [comment]
Yeah I posted it on the subreddit, id thats what you meant

**Comment by itsjoekent** [comment]
Did you find this somewhere else?

**Comment by rthbound** [comment]
I found this on github... just letting you know there's lots of coders
there in case you wanted more hands on keyboards :)

**Comment by itsjoekent** [comment]
oh wow thats cool haha

(sorry im not used to other people finding my stuff on here so im a little more excited then i should be)
